// ------- Goalkeeper Rows ------- //

[ 
    { 
        scorer: { 
            teamName: 'Everton',
            urlName: 'jordan-pickford',
            scorerId: '032f9',
            disableLineupChange: true,
            posIdsNoFlex: [Array],
            posShortNames: 'G',
            team: false,
            icons: [Array],
            rookie: false,
            posIds: [Array],
            teamId: '110050',
            name: 'Jordan Pickford',
            teamShortName: 'EVE',
            shortName: 'J. Pickford' 
        },
        eligibleStatusIds: [ '1', '2' ],
        posId: '704',
        cells:
            [ 
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object] 
            ],
        statusId: '1',
        eligiblePosIds: [ '704' ],
        actions: [ 
            [Object] 
        ] 
    },
    { 
        scorer:
        { 
            teamName: 'Liverpool',
            urlName: 'alisson-ramses-becker',
            scorerId: '04sjt',
            disableLineupChange: true,
            posIdsNoFlex: [Array],
            posShortNames: 'G',
            team: false,
            icons: [Array],
            rookie: false,
            posIds: [Array],
            teamId: '110070',
            name: 'Alisson',
            teamShortName: 'LIV',
            shortName: 'Alisson' },
        eligibleStatusIds: [ '1', '2' ],
        posId: '704',
        cells:
            [ 
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object] 
            ],
        statusId: '2',
        eligiblePosIds: [ '704' ],
        actions: [ 
            [Object] 
        ] 
    },
    { 
        numSpotsAvailableText: 'Reserve spot(s) available',
        description: 'Reserve spot(s) available Limited by Max Players on Team',
        numSpotsAvailableDescription: 'Limited by Max Players on Team',
        numSpotsAvailableIcon: 'LIMITED_BY_MAX',
        cells:
            [ 
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object] 
            ],
        statusId: '2' 
    },
    { 
        scorer: { team: false, rookie: false },
        scorerColumn: 'Totals',
        bold: true,
        cells:
            [ 
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object],
                [Object] 
            ],
        statusId: '9999' 
    } 
]

// -------------------------------------//

// ------- Goalkeeper Row ------- //
[{ 
    scorer: { 
        teamName: 'Everton',
        urlName: 'jordan-pickford',
        scorerId: '032f9',
        disableLineupChange: true,
        posIdsNoFlex: [ '704' ],
        posShortNames: 'G',
        team: false,
        icons: [ [Object] ],
        rookie: false,
        posIds: [ '704' ],
        teamId: '110050',
        name: 'Jordan Pickford',
        teamShortName: 'EVE',
        shortName: 'J. Pickford' 
    },
    eligibleStatusIds: [ '1', '2' ],
    posId: '704',
    cells:[ 
        { eventId: '03p9v', content: 'EVE 0<br/>@BUR 1 F' },
        { content: '6' },
        { content: '6' },
        { content: '1' },
        { content: '0' },
        { content: '1' },
        { content: '2' },
        { content: '0' },
        { content: '0' },
        { content: '0' },
        { content: '0' },
        { content: '4' },
        { content: '3' } 
    ],
    statusId: '1',
    eligiblePosIds: [ '704' ],
    actions: [ { typeId: '4' } ] 
}]    
// -------------------------------------//

// ------- Goalkeeper Header ------- //

{ 
    cells:
        [ 
            { 
                eventStr: true,
                sortDirection: 1,
                name: 'Opponent',
                shortName: 'Opp',
                key: 'opponent' 
            },
            { 
                sortDirection: 1,
                sortKey: 'SCORE',
                sortType: 'SCORE',
                name: 'Fantasy Points',
                shortName: 'FPts',
                key: 'fpts' 
            },
            { 
                sortDirection: 1,
                sortKey: 'FPTS_PER_GAME',
                sortType: 'FPTS_PER_GAME',
                name: 'Average Fantasy Points per Game',
                shortName: 'FP/G',
                key: 'fptsPerGame' 
            },
            { 
                sortDirection: 1,
                sortKey: 'SCORING_CATEGORY_5020#6060#-1',
                scipId: '5020#6060#-1',
                sortType: 'SCORING_CATEGORY',
                name: 'Games Played',
                shortName: 'GP',
                key: '5020#6060#-1' 
            },
            { 
                sortDirection: 1,
                sortKey: 'SCORING_CATEGORY_5020#6250#-1',
                scipId: '5020#6250#-1',
                sortType: 'SCORING_CATEGORY',
                name:
                'Clean Sheets -- Awarded to a player who played at least 60 minutes and whose team gave up 0 goals that game.',
                shortName: 'CS',
                key: '5020#6250#-1' 
            },
            { 
                sortDirection: -1,
                sortKey: 'SCORING_CATEGORY_5020#6112#-1',
                scipId: '5020#6112#-1',
                sortType: 'SCORING_CATEGORY',
                name:
                'Goals Against -- Goals scored by opposing team while the player is on the field',
                shortName: 'GA',
                key: '5020#6112#-1' 
            },
            { 
                sortDirection: 1,
                sortKey: 'SCORING_CATEGORY_5020#6200#-1',
                scipId: '5020#6200#-1',
                sortType: 'SCORING_CATEGORY',
                name: 'Saves',
                shortName: 'Sv',
                key: '5020#6200#-1' 
            },
            { 
                sortDirection: -1,
                sortKey: 'SCORING_CATEGORY_5020#6280#-1',
                scipId: '5020#6280#-1',
                sortType: 'SCORING_CATEGORY',
                name: 'Yellow Cards',
                shortName: 'YC',
                key: '5020#6280#-1' 
            },
            { 
                sortDirection: 1,
                sortKey: 'SCORING_CATEGORY_5020#6170#-1',
                scipId: '5020#6170#-1',
                sortType: 'SCORING_CATEGORY',
                name:
                'Penalty Kick Saves -- Number of penalty kicks saved by the goalie',
                shortName: 'PKS',
                key: '5020#6170#-1' 
            },
            { 
                sortDirection: 1,
                sortKey: 'SCORING_CATEGORY_5020#6002#-1',
                scipId: '5020#6002#-1',
                sortType: 'SCORING_CATEGORY',
                name:
                'Key Passes (Assists on Shots) -- Player assists a shot (including goals)',
                shortName: 'KP',
                key: '5020#6002#-1' 
            },
            { 
                sortDirection: 1,
                sortKey: 'SCORING_CATEGORY_5020#6108#-1',
                scipId: '5020#6108#-1',
                sortType: 'SCORING_CATEGORY',
                name: 'Interceptions -- Player intercepts a pass',
                shortName: 'Int',
                key: '5020#6108#-1' 
            },
            { 
                sortDirection: 1,
                sortKey: 'SCORING_CATEGORY_5020#6016#-1',
                scipId: '5020#6016#-1',
                sortType: 'SCORING_CATEGORY',
                name:
                'Effective Clearances -- Successful defensive clearance - where player under pressure kicks the ball clear of the defensive zone and/or out of play',
                shortName: 'CLR',
                key: '5020#6016#-1' 
            },
            { 
                sortDirection: 1,
                sortKey: 'SCORING_CATEGORY_5020#6007#-1',
                scipId: '5020#6007#-1',
                sortType: 'SCORING_CATEGORY',
                name:
                'Aerials Won -- Successful aerial duels (the definition of an aerial duel is that it is between two players - either both jumping or only one jumping and the other contesting the header by making it difficult to win - and one player has to win the contest with a header OR if it is between an outfield player and a goalkeeper then the goalkeeper is allowed to punch it clear)',
                shortName: 'AER',
                key: '5020#6007#-1' 
            } 
        ] 
}

// -------------------------------------//

// ------- Outfielder Row ------- //

[{ 
    scorer:{ 
        teamName: 'Tottenham Hotspur',
        urlName: 'ben-davies',
        scorerId: '02oo1',
        disableLineupChange: true,
        posIdsNoFlex: [ '703' ],
        posShortNames: 'D',
        team: false,
        icons: [ [Object] ],
        rookie: false,
        posIds: [ '703' ],
        teamId: '110160',
        name: 'Ben Davies',
        teamShortName: 'TOT',
        shortName: 'B. Davies' },
    eligibleStatusIds: [ '1', '2' ],
    posId: '703',
    cells:[ 
        { eventId: '03p9u', content: 'TOT 0<br/>@BHA 3 F' },
        { content: '0' },
        { content: '0' },
        { content: '1' },
        { content: '0' },
        { content: '0' },
        { content: '0' },
        { content: '0' },
        { content: '1' },
        { content: '1' },
        { content: '0' },
        { content: '0' },
        { content: '0' },
        { content: '0' },
        { content: '3' },
        { content: '2' },
        { content: '0' },
        { content: '2' },
        { content: '0' },
        { content: '0' },
        { content: '0' },
        { content: '3' },
        { content: '0' } 
    ],
    statusId: '1',
    eligiblePosIds: [ '703' ],
    actions: [ { typeId: '4' } ] 
}]

// -------------------------------------//

// ------- Outfielder Rows ------- //

[ { 
    scorer:{ 
        teamName: 'Tottenham Hotspur',
        urlName: 'ben-davies',
        scorerId: '02oo1',
        disableLineupChange: true,
        posIdsNoFlex: [Array],
        posShortNames: 'D',
        team: false,
        icons: [Array],
        rookie: false,
        posIds: [Array],
        teamId: '110160',
        name: 'Ben Davies',
        teamShortName: 'TOT',
        shortName: 'B. Davies' },
    eligibleStatusIds: [ '1', '2' ],
    posId: '703',
    cells:[ 
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
    statusId: '1',
    eligiblePosIds: [ '703' ],
    actions: [ [Object] ] 
},
{ 
    scorer:{ 
        teamName: 'Watford',
        urlName: 'jose-holebas',
        scorerId: '03rn2',
        disableLineupChange: true,
        posIdsNoFlex: [Array],
        posShortNames: 'D',
        team: false,
        icons: [Array],
        rookie: false,
        posIds: [Array],
        teamId: '110165',
        name: 'José Holebas',
        teamShortName: 'WAT',
        shortName: 'J. Holebas' 
    },
    eligibleStatusIds: [ '1', '2' ],
    posId: '703',
    cells:[ 
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] 
    ],
    statusId: '1',
    eligiblePosIds: [ '703' ],
    actions: [ [Object] ] 
},
{ 
    scorer:{ 
        teamName: 'Sheffield United',
        urlName: 'enda-stevens',
        scorerId: '02lmo',
        disableLineupChange: true,
        posIdsNoFlex: [Array],
        posShortNames: 'D',
        team: false,
        icons: [Array],
        rookie: false,
        posIds: [Array],
        teamId: '110127',
        name: 'Enda Stevens',
        teamShortName: 'SHU',
        shortName: 'E. Stevens' 
    },
    eligibleStatusIds: [ '1', '2' ],
    posId: '703',
    cells:[ 
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] 
    ],
    statusId: '1',
    eligiblePosIds: [ '703' ],
    actions: [ [Object] ] 
},
{ 
    posId: '703',
    cells:[ 
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] 
    ],
    statusId: '1' 
},
{ 
    posId: '703',
    cells:[ 
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] 
    ],
    statusId: '1' 
},
{ 
    scorer:{ 
        teamName: 'Everton',
        urlName: 'alex-iwobi',
        scorerId: '038ze',
        disableLineupChange: true,
        posIdsNoFlex: [Array],
        posShortNames: 'M',
        team: false,
        icons: [Array],
        rookie: false,
        posIds: [Array],
        teamId: '110050',
        name: 'Alex Iwobi',
        teamShortName: 'EVE',
        shortName: 'A. Iwobi' },
    eligibleStatusIds: [ '1', '2' ],
    posId: '702',
    cells:[ 
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
    statusId: '1',
    eligiblePosIds: [ '702' ],
    actions: [ [Object] ] 
},
{ 
    scorer:{ 
        teamName: 'West Ham United',
        urlName: 'manuel-lanzini',
        scorerId: '03sd5',
        disableLineupChange: true,
        posIdsNoFlex: [Array],
        posShortNames: 'M',
        team: false,
        icons: [Array],
        rookie: false,
        posIds: [Array],
        teamId: '110175',
        name: 'Manuel Lanzini',
        teamShortName: 'WHU',
        shortName: 'M. Lanzini' },
    eligibleStatusIds: [ '1', '2' ],
    posId: '702',
    cells:[ 
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] 
    ],
    statusId: '1',
    eligiblePosIds: [ '702' ],
    actions: [ [Object] ] 
},
{ 
    scorer:{ 
        teamName: 'Watford',
        urlName: 'roberto-pereyra',
        scorerId: '046v3',
        disableLineupChange: true,
        posIdsNoFlex: [Array],
        posShortNames: 'M',
        team: false,
        icons: [Array],
        rookie: false,
        posIds: [Array],
        teamId: '110165',
        name: 'Roberto Pereyra',
        teamShortName: 'WAT',
        shortName: 'R. Pereyra' },
    eligibleStatusIds: [ '1', '2' ],
    posId: '702',
    cells:[ 
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] 
    ],
    statusId: '1',
    eligiblePosIds: [ '702' ],
    actions: [ [Object] ] 
},
{ 
    scorer:{ 
        teamName: 'Wolverhampton',
        urlName: 'ruben-diogo-da-silva-neves',
        scorerId: '04qr6',
        disableLineupChange: true,
        posIdsNoFlex: [Array],
        posShortNames: 'M',
        team: false,
        icons: [Array],
        rookie: false,
        posIds: [Array],
        teamId: '110191',
        name: 'Rúben Neves',
        teamShortName: 'WOL',
        shortName: 'Rúben Neves' },
    eligibleStatusIds: [ '1', '2' ],
    posId: '702',
    cells:[ 
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] 
    ],
    statusId: '1',
    eligiblePosIds: [ '702' ],
    actions: [ [Object] ] 
},
{ 
    posId: '702',
    cells:[ 
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] 
    ],
    statusId: '1' 
},
{ 
    scorer:{ 
        teamName: 'Chelsea',
        urlName: 'tammy-abraham',
        scorerId: '0410j',
        disableLineupChange: true,
        posIdsNoFlex: [Array],
        posShortNames: 'F',
        team: false,
        icons: [Array],
        rookie: false,
        posIds: [Array],
        teamId: '110040',
        name: 'Tammy Abraham',
        teamShortName: 'CHE',
        shortName: 'T. Abraham' },
    eligibleStatusIds: [ '1', '2' ],
    posId: '701',
    cells:[ 
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] 
    ],
    statusId: '1',
    eligiblePosIds: [ '701' ],
    actions: [ [Object] ] 
},
{ 
    scorer:{ 
        teamName: 'Southampton',
        urlName: 'daniel-ings',
        scorerId: '03dxq',
        disableLineupChange: true,
        posIdsNoFlex: [Array],
        posShortNames: 'F',
        team: false,
        icons: [Array],
        rookie: false,
        posIds: [Array],
        teamId: '110135',
        name: 'Danny Ings',
        teamShortName: 'SOU',
        shortName: 'Danny Ings' },
    eligibleStatusIds: [ '1', '2' ],
    posId: '701',
    cells:[ 
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] 
    ],
    statusId: '1',
    eligiblePosIds: [ '701' ],
    actions: [ [Object] ] 
},
{ 
    scorer:{ 
        teamName: 'Arsenal',
        urlName: 'nicolas-pepe',
        scorerId: '055sk',
        disableLineupChange: true,
        posIdsNoFlex: [Array],
        posShortNames: 'F',
        team: false,
        icons: [Array],
        rookie: false,
        posIds: [Array],
        teamId: '110000',
        name: 'Nicolas Pépé',
        teamShortName: 'ARS',
        shortName: 'N. Pépé' },
    eligibleStatusIds: [ '1', '2' ],
    posId: '701',
    cells:[ 
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] 
    ],
    statusId: '1',
    eligiblePosIds: [ '701' ],
    actions: [ [Object] ] 
},
{ 
    scorer:{ 
        teamName: 'Leicester City',
        urlName: 'ricardo-domingos-barbosa-pereira',
        scorerId: '04qfy',
        disableLineupChange: true,
        posIdsNoFlex: [Array],
        posShortNames: 'D',
        team: false,
        icons: [Array],
        rookie: false,
        posIds: [Array],
        teamId: '110230',
        name: 'Ricardo Pereira',
        teamShortName: 'LEI',
        shortName: 'Ricardo Pereira' },
    eligibleStatusIds: [ '1', '2' ],
    posId: '703',
    cells:[ 
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] 
    ],
    statusId: '2',
    eligiblePosIds: [ '703' ],
    actions: [ [Object] ] 
},
{ 
    scorer:{ 
        teamName: 'Bournemouth',
        urlName: 'ryan-fraser',
        scorerId: '03r8r',
        disableLineupChange: true,
        posIdsNoFlex: [Array],
        posShortNames: 'M',
        team: false,
        icons: [Array],
        rookie: false,
        posIds: [Array],
        teamId: '110033',
        name: 'Ryan Fraser',
        teamShortName: 'BOU',
        shortName: 'R. Fraser' },
    eligibleStatusIds: [ '1', '2' ],
    posId: '702',
    cells:[ 
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] 
    ],
    statusId: '2',
    eligiblePosIds: [ '702' ],
    actions: [ [Object] ] 
},
{ 
    scorer:{ 
        teamName: 'Tottenham Hotspur',
        urlName: 'lucas-rodrigues-moura-da-silva',
        scorerId: '04mqz',
        disableLineupChange: true,
        posIdsNoFlex: [Array],
        posShortNames: 'M',
        team: false,
        icons: [Array],
        rookie: false,
        posIds: [Array],
        teamId: '110160',
        name: 'Lucas Moura',
        teamShortName: 'TOT',
        shortName: 'Lucas Moura' },
    eligibleStatusIds: [ '1', '2' ],
    posId: '702',
    cells:[ 
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] 
    ],
    statusId: '2',
    eligiblePosIds: [ '702' ],
    actions: [ [Object] ] 
},
{ 
    scorer:{ 
        teamName: 'Crystal Palace',
        urlName: 'andros-townsend',
        scorerId: '02lp7',
        disableLineupChange: true,
        posIdsNoFlex: [Array],
        posShortNames: 'M',
        team: false,
        icons: [Array],
        rookie: false,
        posIds: [Array],
        teamId: '110045',
        name: 'Andros Townsend',
        teamShortName: 'CRY',
        shortName: 'A. Townsend' },
    eligibleStatusIds: [ '1', '2' ],
    posId: '702',
    cells:[ 
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] 
    ],
    statusId: '2',
    eligiblePosIds: [ '702' ],
    actions: [ [Object] ] 
},
{ 
    numSpotsAvailableText: 'Reserve spot(s) available',
    description: 'Reserve spot(s) available Limited by Max Players on Team',
    numSpotsAvailableDescription: 'Limited by Max Players on Team',
    numSpotsAvailableIcon: 'LIMITED_BY_MAX',
    cells:[ 
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] 
    ],
    statusId: '2' 
},
{ 
    scorer: { 
        team: false, 
        rookie: false 
    },
    scorerColumn: 'Totals',
    bold: true,
    cells:[ 
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] 
    ],
    statusId: '9999' 
} ]

// -------------------------------------//

// ------- Outfielder Header ------- //

[{ cells:[ 
    { 
        eventStr: true,
        sortDirection: 1,
        name: 'Opponent',
        shortName: 'Opp',
        key: 'opponent' 
    },
    { 
        sortDirection: 1,
        sortKey: 'SCORE',
        sortType: 'SCORE',
        name: 'Fantasy Points',
        shortName: 'FPts',
        key: 'fpts' 
    },
    { 
        sortDirection: 1,
        sortKey: 'FPTS_PER_GAME',
        sortType: 'FPTS_PER_GAME',
        name: 'Average Fantasy Points per Game',
        shortName: 'FP/G',
        key: 'fptsPerGame' 
    },
    { 
        sortDirection: 1,
        sortKey: 'SCORING_CATEGORY_5010#6060#-1',
        scipId: '5010#6060#-1',
        sortType: 'SCORING_CATEGORY',
        name: 'Games Played',
        shortName: 'GP',
        key: '5010#6060#-1' 
    },
    { 
        sortDirection: 1,
        sortKey: 'SCORING_CATEGORY_5010#6090#-1',
        scipId: '5010#6090#-1',
        sortType: 'SCORING_CATEGORY',
        name: 'Goals',
        shortName: 'G',
        key: '5010#6090#-1' 
    },
    { 
        sortDirection: 1,
        sortKey: 'SCORING_CATEGORY_5010#6002#-1',
        scipId: '5010#6002#-1',
        sortType: 'SCORING_CATEGORY',
        name:
         'Key Passes (Assists on Shots) -- Player assists a shot (including goals)',
        shortName: 'KP',
        key: '5010#6002#-1' 
    },
    { 
        sortDirection: 1,
        sortKey: 'SCORING_CATEGORY_5010#6362#-1',
        scipId: '5010#6362#-1',
        sortType: 'SCORING_CATEGORY',
        name: 'Assists (Total)\t -- Official Assists + Fantasy Assists',
        shortName: 'AT',
        key: '5010#6362#-1' 
    },
    { 
        sortDirection: 1,
        sortKey: 'SCORING_CATEGORY_5010#6230#-1',
        scipId: '5010#6230#-1',
        sortType: 'SCORING_CATEGORY',
        name: 'Shots on Target',
        shortName: 'SOT',
        key: '5010#6230#-1' 
    },
    { 
        sortDirection: 1,
        sortKey: 'SCORING_CATEGORY_5010#6256#-1',
        scipId: '5010#6256#-1',
        sortType: 'SCORING_CATEGORY',
        name:
         'Tackles Won -- Total tackles won (winning possession or putting the ball out of play)',
        shortName: 'TkW',
        key: '5010#6256#-1' 
    },
    { 
        sortDirection: 1,
        sortKey: 'SCORING_CATEGORY_5010#6039#-1',
        scipId: '5010#6039#-1',
        sortType: 'SCORING_CATEGORY',
        name: 'Dispossessed',
        shortName: 'DIS',
        key: '5010#6039#-1' 
    },
    { 
        sortDirection: -1,
        sortKey: 'SCORING_CATEGORY_5010#6280#-1',
        scipId: '5010#6280#-1',
        sortType: 'SCORING_CATEGORY',
        name: 'Yellow Cards',
        shortName: 'YC',
        key: '5010#6280#-1' 
    },
    { 
        sortDirection: -1,
        sortKey: 'SCORING_CATEGORY_5010#6281#-1',
        scipId: '5010#6281#-1',
        sortType: 'SCORING_CATEGORY',
        name: 'Second Yellow Cards',
        shortName: 'SYC',
        key: '5010#6281#-1' 
    },
    { 
        sortDirection: -1,
        sortKey: 'SCORING_CATEGORY_5010#6190#-1',
        scipId: '5010#6190#-1',
        sortType: 'SCORING_CATEGORY',
        name:
         'Red Cards -- If a player receives a red card and then has his red card rescinded at a later time, his red card will remain (i.e. he will have credit for both a red card and a red card rescinded).',
        shortName: 'RC',
        key: '5010#6190#-1' 
    },
    { 
        sortDirection: 1,
        sortKey: 'SCORING_CATEGORY_5010#6029#-1',
        scipId: '5010#6029#-1',
        sortType: 'SCORING_CATEGORY',
        name:
         'Accurate Crosses (No Corners) -- Same as Accurate Crosses, but excludes corners',
        shortName: 'ACNC',
        key: '5010#6029#-1' 
    },
    { 
        sortDirection: 1,
        sortKey: 'SCORING_CATEGORY_5010#6108#-1',
        scipId: '5010#6108#-1',
        sortType: 'SCORING_CATEGORY',
        name: 'Interceptions -- Player intercepts a pass',
        shortName: 'Int',
        key: '5010#6108#-1' 
    },
    { 
        sortDirection: 1,
        sortKey: 'SCORING_CATEGORY_5010#6016#-1',
        scipId: '5010#6016#-1',
        sortType: 'SCORING_CATEGORY',
        name:
         'Effective Clearances -- Successful defensive clearance - where player under pressure kicks the ball clear of the defensive zone and/or out of play',
        shortName: 'CLR',
        key: '5010#6016#-1' 
    },
    { 
        sortDirection: 1,
        sortKey: 'SCORING_CATEGORY_5010#6019#-1',
        scipId: '5010#6019#-1',
        sortType: 'SCORING_CATEGORY',
        name:
         'Successful Dribbles (Contests Succeeded) -- Total dribbles where a player beats an opponent - no overruns',
        shortName: 'CoS',
        key: '5010#6019#-1' 
    },
    { 
        sortDirection: 1,
        sortKey: 'SCORING_CATEGORY_5010#6007#-1',
        scipId: '5010#6007#-1',
        sortType: 'SCORING_CATEGORY',
        name:
         'Aerials Won -- Successful aerial duels (the definition of an aerial duel is that it is between two players - either both jumping or only one jumping and the other contesting the header by making it difficult to win - and one player has to win the contest with a header OR if it is between an outfield player and a goalkeeper then the goalkeeper is allowed to punch it clear)',
        shortName: 'AER',
        key: '5010#6007#-1' 
    },
    { 
        sortDirection: 1,
        sortKey: 'SCORING_CATEGORY_5010#6106#-1',
        scipId: '5010#6106#-1',
        sortType: 'SCORING_CATEGORY',
        name: 'Hat Tricks -- Player scores 3 goals in a game',
        shortName: 'HT',
        key: '5010#6106#-1' 
    },
    { 
        sortDirection: -1,
        sortKey: 'SCORING_CATEGORY_5010#6332#-1',
        scipId: '5010#6332#-1',
        sortType: 'SCORING_CATEGORY',
        name:
         'Penalty Kicks Missed -- Number of penalty kicks where the shooter did not score',
        shortName: 'PKM',
        key: '5010#6332#-1' 
    },
    { 
        sortDirection: -1,
        sortKey: 'SCORING_CATEGORY_5010#6105#-1',
        scipId: '5010#6105#-1',
        sortType: 'SCORING_CATEGORY',
        name: 'Own Goals -- Goals scored on own net',
        shortName: 'OG',
        key: '5010#6105#-1' 
    },
    { 
        sortDirection: -1,
        sortKey: 'SCORING_CATEGORY_5010#6101#-1',
        scipId: '5010#6101#-1',
        sortType: 'SCORING_CATEGORY',
        name:
         'Goals Against Outfielders  -- Goals conceded by the team while the player was on the field. Any outfielder will get credit for this stat.',
        shortName: 'GAO',
        key: '5010#6101#-1' 
    },
    { 
        sortDirection: 1,
        sortKey: 'SCORING_CATEGORY_5010#6249#-1',
        scipId: '5010#6249#-1',
        sortType: 'SCORING_CATEGORY',
        name:
         'Clean Sheets On Field -- Awarded to a player who played at least 60 minutes and whose team gave up 0 goals during the time the player was on the field, even if a goal was scored after the player left the field',
        shortName: 'CS',
        key: '5010#6249#-1' 
    } 
] }]

// -------------------------------------//

// --------- Player Stats --------------//

[{
    "_id" : "neoNXa7yYwYiT3E9r",
    "team" : 0,
    "GK" : {
            "id" : "032f9",
            "pos" : "G",
            "name" : "Jordan Pickford",
            "club" : "EVE",
            "stats" : {
                    "FPts" : 6,
                    "FPpG" : 6,
                    "GP" : 1,
                    "CS" : 0,
                    "GA" : 1,
                    "Sv" : 2,
                    "YC" : 0,
                    "PKS" : 0,
                    "KP" : 0,
                    "Int" : 0,
                    "CLR" : 4,
                    "AER" : 3,
                    "RC" : 0
            }
    },
    "OF" : [
            {
                    "id" : "02oo1",
                    "pos" : "D",
                    "name" : "Ben Davies",
                    "club" : "TOT",
                    "stats" : {
                            "FPts" : 0,
                            "FPpG" : 0,
                            "GP" : 1,
                            "G" : 0,
                            "KP" : 0,
                            "AT" : 0,
                            "SOT" : 0,
                            "TkW" : 1,
                            "DIS" : 1,
                            "YC" : 0,
                            "SYC" : 0,
                            "RC" : 0,
                            "ACNC" : 0,
                            "Int" : 3,
                            "CLR" : 2,
                            "CoS" : 0,
                            "AER" : 2,
                            "HT" : 0,
                            "PKM" : 0,
                            "OG" : 0,
                            "GAO" : 3,
                            "CS" : 0
                    }
            },
            {
                    "id" : "03rn2",
                    "pos" : "D",
                    "name" : "José Holebas",
                    "club" : "WAT",
                    "stats" : {
                            "FPts" : 13,
                            "FPpG" : 13,
                            "GP" : 1,
                            "G" : 0,
                            "KP" : 0,
                            "AT" : 0,
                            "SOT" : 0,
                            "TkW" : 1,
                            "DIS" : 0,
                            "YC" : 0,
                            "SYC" : 0,
                            "RC" : 0,
                            "ACNC" : 0,
                            "Int" : 1,
                            "CLR" : 4,
                            "CoS" : 1,
                            "AER" : 3,
                            "HT" : 0,
                            "PKM" : 0,
                            "OG" : 0,
                            "GAO" : 0,
                            "CS" : 1
                    }
            },
            {
                    "id" : "02lmo",
                    "pos" : "D",
                    "name" : "Enda Stevens",
                    "club" : "SHU",
                    "stats" : {
                            "FPts" : 11,
                            "FPpG" : 11,
                            "GP" : 1,
                            "G" : 0,
                            "KP" : 0,
                            "AT" : 0,
                            "SOT" : 0,
                            "TkW" : 2,
                            "DIS" : 3,
                            "YC" : 0,
                            "SYC" : 0,
                            "RC" : 0,
                            "ACNC" : 1,
                            "Int" : 3,
                            "CLR" : 1,
                            "CoS" : 0,
                            "AER" : 1,
                            "HT" : 0,
                            "PKM" : 0,
                            "OG" : 0,
                            "GAO" : 0,
                            "CS" : 1
                    }
            },
            {
                    "id" : "038ze",
                    "pos" : "M",
                    "name" : "Alex Iwobi",
                    "club" : "EVE",
                    "stats" : {
                            "FPts" : 5,
                            "FPpG" : 5,
                            "GP" : 1,
                            "G" : 0,
                            "KP" : 1,
                            "AT" : 0,
                            "SOT" : 0,
                            "TkW" : 1,
                            "DIS" : 1,
                            "YC" : 0,
                            "SYC" : 0,
                            "RC" : 0,
                            "ACNC" : 1,
                            "Int" : 0,
                            "CLR" : 0,
                            "CoS" : 1,
                            "AER" : 2,
                            "HT" : 0,
                            "PKM" : 0,
                            "OG" : 0,
                            "GAO" : 1,
                            "CS" : 0
                    }
            },
            {
                    "id" : "03sd5",
                    "pos" : "M",
                    "name" : "Manuel Lanzini",
                    "club" : "WHU",
                    "stats" : {
                            "FPts" : 1,
                            "FPpG" : 1,
                            "GP" : 1,
                            "G" : 0,
                            "KP" : 0,
                            "AT" : 0,
                            "SOT" : 0,
                            "TkW" : 0,
                            "DIS" : 0,
                            "YC" : 0,
                            "SYC" : 0,
                            "RC" : 0,
                            "ACNC" : 1,
                            "Int" : 0,
                            "CLR" : 0,
                            "CoS" : 0,
                            "AER" : 0,
                            "HT" : 0,
                            "PKM" : 0,
                            "OG" : 0,
                            "GAO" : 1,
                            "CS" : 0
                    }
            },
            {
                    "id" : "046v3",
                    "pos" : "M",
                    "name" : "Roberto Pereyra",
                    "club" : "WAT",
                    "stats" : {
                            "FPts" : 4,
                            "FPpG" : 4,
                            "GP" : 1,
                            "G" : 0,
                            "KP" : 1,
                            "AT" : 0,
                            "SOT" : 0,
                            "TkW" : 0,
                            "DIS" : 0,
                            "YC" : 0,
                            "SYC" : 0,
                            "RC" : 0,
                            "ACNC" : 0,
                            "Int" : 0,
                            "CLR" : 0,
                            "CoS" : 1,
                            "AER" : 0,
                            "HT" : 0,
                            "PKM" : 0,
                            "OG" : 0,
                            "GAO" : 0,
                            "CS" : 1
                    }
            },
            {
                    "id" : "04qr6",
                    "pos" : "M",
                    "name" : "Rúben Neves",
                    "club" : "WOL",
                    "stats" : {
                            "FPts" : 1,
                            "FPpG" : 1,
                            "GP" : 1,
                            "G" : 0,
                            "KP" : 0,
                            "AT" : 0,
                            "SOT" : 0,
                            "TkW" : 1,
                            "DIS" : 1,
                            "YC" : 1,
                            "SYC" : 0,
                            "RC" : 0,
                            "ACNC" : 0,
                            "Int" : 3,
                            "CLR" : 3,
                            "CoS" : 0,
                            "AER" : 0,
                            "HT" : 0,
                            "PKM" : 0,
                            "OG" : 0,
                            "GAO" : 0,
                            "CS" : 1
                    }
            },
            {
                    "id" : "0410j",
                    "pos" : "F",
                    "name" : "Tammy Abraham",
                    "club" : "CHE",
                    "stats" : {
                            "FPts" : 17,
                            "FPpG" : 17,
                            "GP" : 1,
                            "G" : 1,
                            "KP" : 1,
                            "AT" : 0,
                            "SOT" : 3,
                            "TkW" : 0,
                            "DIS" : 3,
                            "YC" : 0,
                            "SYC" : 0,
                            "RC" : 0,
                            "ACNC" : 0,
                            "Int" : 0,
                            "CLR" : 1,
                            "CoS" : 0,
                            "AER" : 3,
                            "HT" : 0,
                            "PKM" : 0,
                            "OG" : 0,
                            "GAO" : 1,
                            "CS" : 0
                    }
            },
            {
                    "id" : "03dxq",
                    "pos" : "F",
                    "name" : "Danny Ings",
                    "club" : "SOU",
                    "stats" : {
                            "FPts" : 17,
                            "FPpG" : 17,
                            "GP" : 1,
                            "G" : 1,
                            "KP" : 1,
                            "AT" : 0,
                            "SOT" : 2,
                            "TkW" : 1,
                            "DIS" : 0,
                            "YC" : 0,
                            "SYC" : 0,
                            "RC" : 0,
                            "ACNC" : 0,
                            "Int" : 0,
                            "CLR" : 0,
                            "CoS" : 1,
                            "AER" : 0,
                            "HT" : 0,
                            "PKM" : 0,
                            "OG" : 0,
                            "GAO" : 3,
                            "CS" : 0
                    }
            },
            {
                    "id" : "055sk",
                    "pos" : "F",
                    "name" : "Nicolas Pépé",
                    "club" : "ARS",
                    "stats" : {
                            "FPts" : 10,
                            "FPpG" : 10,
                            "GP" : 1,
                            "G" : 0,
                            "KP" : 1,
                            "AT" : 1,
                            "SOT" : 0,
                            "TkW" : 1,
                            "DIS" : 3,
                            "YC" : 0,
                            "SYC" : 0,
                            "RC" : 0,
                            "ACNC" : 0,
                            "Int" : 0,
                            "CLR" : 0,
                            "CoS" : 2,
                            "AER" : 1,
                            "HT" : 0,
                            "PKM" : 0,
                            "OG" : 0,
                            "GAO" : 0,
                            "CS" : 1
                    }
            }
    ]
}]

// ------------------------------------- //